name: Script Verification

on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Script
        run: |
          sudo host_serial=$(dmidecode -s system-serial-number)
          sudo echo "Registering host with serial number: $host_serial"
          sudo chmod +x ./mason.sh
          sudo ./mason.sh -d
